version: 0.0
os: linux
files:
  - source: /
    destination: /var/api/
hooks:
  AfterInstall:
   - location: scripts/npm-install.sh
     timeout: 180
     runas: root
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60