version: 0.0
os: linux
hooks:
  AfterInstall:
   - location: scripts/npm-install.sh
     timeout: 180
     runas: root
  ApplicationStart:
    - location: srcipts/npm-start.sh
      runas: root
      timeout: 60