version: 0.0
os: linux
hooks:
  AfterInstall:
   - location: ./webapp/scripts/npm-install.sh
     timeout: 180
     runas: root
  ApplicationStart:
    - location: ./webapp/srcipts/npm-start.sh
      runas: root
      timeout: 60