version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
   - location: scripts/npm-install.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: ubuntu
      timeout: 60