# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: 'dev'
          aws-access-key-id: $AWS_ACCESS_KEY
          aws-secret-access-key: $Secret_access_key
          aws-region: $AWS_REGION

      - run: echo "Run your code here"
  pr_check:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: circleci/mariadb:10.2
        environment:
          MYSQL_TCP_PORT: $DB_PORT
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: $DBNAME
          MYSQL_USER: $DB_USERNAME
          MYSQL_PASSWORD: $DB_PASSWORD

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir bucket && echo "test test" > bucket/build_asset.txt

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      #- run: node server.js
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: mkdir bucket && echo "test test" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          overwrite: true
          to: 's3://$bucket_name/webapp'
      - aws-s3/copy:
          arguments: '--dry-run'
          from: bucket/build_asset.txt
          to: 's3://$bucket_name'
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: circleci/mariadb:10.2
        environment:
          MYSQL_TCP_PORT: $DB_PORT
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: $DBNAME
          MYSQL_USER: $DB_USERNAME
          MYSQL_PASSWORD: $DB_PASSWORD

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      #- run: node server.js

      - save_cache:
          paths:
            - node_modules

          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test


workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli
  pr-check:
    jobs:
      - pr_check
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

