# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  pr_check:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: circleci/mariadb:10.2
        environment:
          MYSQL_TCP_PORT: $DB_PORT
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: $DBNAME
          MYSQL_USER: $DB_USERNAME
          MYSQL_PASSWORD: $DB_PASSWORD

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      #- run: node server.js
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: 
          name: Install AWSCLI
          command : |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws configure set default.region ${AWS_REGION} --profile ${AWS_PROFILE}
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
            aws configure set aws_secret_access_key ${Secret_access_key}
            echo 'CLI configured for profile' ${AWS_PROFILE}
      - run:
          name: Build artifacts
          command: |
            pwd
            npm build
            mkdir -p codedeploy_artifacts
            pwd
            cd codedeploy_artifacts
            ls -a
            pws
            cp ../*.json .
            cp ../*.md .
            cp ../*.js .
            cp -r ../src/*router .
            cp -r ../src/*service .
            cp -r ../src/*Dao .
            cp -r ../src/*utils .
            cp -r ../src/*constants .
            pwd
            zip -r csye6225-webapp.zip . -i .
            ls -a
            aws s3 cp csye6225-webapp.zip s3://${bucket_name} --sse
            echo 'upload to s3 done'

  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: circleci/mariadb:10.2
        environment:
          MYSQL_TCP_PORT: $DB_PORT
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: $DBNAME
          MYSQL_USER: $DB_USERNAME
          MYSQL_PASSWORD: $DB_PASSWORD

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      #- run: node server.js

      - save_cache:
          paths:
            - node_modules

          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test


workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli
  pr-check:
    jobs:
      - pr_check
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

